###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/20/2017
#   @package        :   Door Sensors
#   @description    :   Door Sensor Stuff
###############################################################################
homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'doorsensors'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    group.doors:
      order: 20

    # Entry Door Sensors
    zwave.ecolink_door_sensor_2:
      friendly_name: Front Door Sensor
    binary_sensor.ecolink_door_sensor_sensor_2:
      friendly_name: Front Door

    zwave.ecolink_door_sensor:
      friendly_name: Back Door Sensor
    binary_sensor.ecolink_door_sensor_sensor:
      friendly_name: Back Door

group:
  Doors:
    entities:
      - binary_sensor.ecolink_door_sensor_sensor
      - binary_sensor.ecolink_door_sensor_sensor_2
      - automation.notify_entry_door_status

sensor:
  - platform: template
    sensors:
      front_door_sensor_battery:
        value_template: "{{ (states.zwave.ecolink_door_sensor_2.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Front Door Sensor Battery
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.front_door_sensor_battery')|int('unknown') %}
          {% if battery_level == -1 %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      back_door_sensor_battery:
        value_template: "{{ (states.zwave.ecolink_door_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Back Door Sensor Battery
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.back_door_sensor_battery')|int('unknown') %}
          {% if battery_level == -1 %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

automation:

  - alias: Notify Entry Door Status
    initial_state: true
    trigger:
      platform: state
      entity_id: 
        - binary_sensor.ecolink_door_sensor_sensor_2
        - binary_sensor.ecolink_door_sensor_sensor
    condition:
      - condition: template
        value_template: "{% if trigger.from_state %} True {% else %} False {% endif %}"
    action:
      - service: script.voice_notify
        data_template:
          value1: >
            {% if trigger.to_state.state | lower == "on" %}
              Your {{ trigger.to_state.attributes.friendly_name }} is OPEN!
            {% elif trigger.to_state.state | lower == "off" %}
              Your {{ trigger.to_state.attributes.friendly_name }} is CLOSED!
            {% endif %}
          greeting: 'no'
          only_at_night: 'yes'