###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Multi Sensors
#   @description    :   Multi Sensor Stuff
###############################################################################
homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'settings'

      exposed: &exposed
        <<: *customize
        emulated_hue: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    zwave.aeotec_zw074_multisensor_gen5_2:
      friendly_name: Upstairs Multi Sensor
      <<: *hidden
    zwave.aeotec_zw074_multisensor_gen5:
      friendly_name: TV Room Multi Sensor
      <<: *hidden
    zwave.aeotec_zw100_multisensor_6:
      friendly_name: Front Room Multi Sensor
      <<: *hidden
      
# TV Room
    binary_sensor.aeotec_zw074_multisensor_gen5_sensor:
      friendly_name: TV Room Motion
      device_class: motion
    sensor.aeotec_zw074_multisensor_gen5_temperature:
      friendly_name: TV Room Temperature
    sensor.aeotec_zw074_multisensor_gen5_luminance:
      friendly_name: TV Room Light Level
    sensor.aeotec_zw074_multisensor_gen5_relative_humidity:
      friendly_name: TV Room Humidity

# Upstairs
    binary_sensor.aeotec_zw074_multisensor_gen5_sensor_2:
      friendly_name: Upstairs Motion
      device_class: motion
    sensor.aeotec_zw074_multisensor_gen5_temperature_2:
      friendly_name: Upstairs Temperature
    sensor.aeotec_zw074_multisensor_gen5_luminance_2:
      friendly_name: Upstairs Light Level
    sensor.aeotec_zw074_multisensor_gen5_relative_humidity_2:
      friendly_name: Upstairs Humidity

# Front Room
    binary_sensor.aeotec_zw100_multisensor_6_sensor:
      friendly_name: Front Room Motion
      device_class: motion
    sensor.aeotec_zw100_multisensor_6_temperature:
      friendly_name: Front Room Temperature
    sensor.aeotec_zw100_multisensor_6_luminance:
      friendly_name: Front Room Light Level
    sensor.aeotec_zw100_multisensor_6_relative_humidity:
      friendly_name: Front Room Humidity
    sensor.aeotec_zw100_multisensor_6_ultraviolet:
      friendly_name: Front Room UV Level

# Automation Stuff
    automation.motion001:
      friendly_name: Motion ON, TV On, Light On
      icon: mdi:run-fast
    automation.motion002:
      friendly_name: Motion ON, TV On, Light Off
      icon: mdi:run-fast
    automation.motion003:
      friendly_name: Motion ON, TV Off, Light On
      icon: mdi:run-fast
    automation.motion004:
      friendly_name: Motion ON, TV Off, Light Off
      icon: mdi:run-fast
    automation.motion005:
      friendly_name: Motion OFF, TV On, Light On
      icon: mdi:run-fast
    automation.motion007:
      friendly_name: Motion OFF, TV Off, Light On
      icon: mdi:run-fast

    automation.upstairs_motion_off:
      friendly_name: Motion Off
      icon: mdi:run-fast
    automation.upstairs_motion_on:
      friendly_name: Motion On
      icon: mdi:run-fast  

group:
  Downstairs Motion Automations:
    entities:
      - automation.motion001
      - automation.motion002
      - automation.motion003
      - automation.motion004
      - automation.motion005
      - automation.motion007
      
  Upstairs Motion Automations:
    entities:
      - automation.upstairs_motion_off
      - automation.upstairs_motion_on
      
  Front Room Motion Automations:
    entities:
      - automation.front_room_motion_off
      - automation.front_room_motion_on

sensor:
  - platform: template
    sensors:
      downstairs_multisensor_battery:
        value_template: "{{ (states.zwave.aeotec_zw074_multisensor_gen5.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Downstairs Multisensor Battery
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.downstairs_multisensor_battery')|int('unknown')  %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      upstairs_multisensor_battery:
        value_template: "{{ (states.zwave.aeotec_zw074_multisensor_gen5_2.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Upstairs Multisensor Battery
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.upstairs_multisensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      frontroom_multisensor_battery:
        value_template: "{{ (states.zwave.aeotec_zw100_multisensor_6.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Front Room Multisensor Battery
        unit_of_measurement: "%"
        icon_template: >-
           {% set battery_level = states('sensor.frontroom_multisensor_battery')|int('unknown') %}
           {% if battery_level == 'unknown' %}
             mdi:battery-unknown
           {% else %}
             {% set battery_round = (battery_level|int / 10)|int * 10 %}
             {% if battery_round >= 100 %}
               mdi:battery
             {% elif battery_round > 0 %}
               mdi:battery-{{ battery_round }}
             {% else %}
               mdi:battery-alert
             {% endif %}
           {% endif %}

automation:
###############################################################################
# Motion Sensor - Downstairs  
###############################################################################  

#===============================================================================================#
#   Automation      It's Dark 	Motion		TV		Lights	ACTION                              #
#===============================================================================================#
#   MOTION001       YES		    ON		    ON		ON		Dim Lights                          #
#   MOTION002       YES		    ON		    ON		OFF		Dim Lights                          #
#   MOTION003       YES		    ON		    OFF		ON		Increase the brightness to 100%     #
#   MOTION004       YES		    ON		    OFF		OFF		Turn Lights ON at 100% brightness   #
#===============================================================================================#
#   MOTION005       YES		    OFF		    ON		ON		Lights OFF                          #
#   MOTION006       YES		    OFF		    ON		OFF		Don't to anything                   #
#   MOTION007       YES		    OFF		    OFF		ON		Turn Lights OFF                     #
#   MOTION008       YES		    OFF		    OFF		OFF		Don't to anything                   #
#===============================================================================================#

#===============================================================================================#
#   Automation      It's Dark 	Motion		TV		Lights	ACTION                              #
#   MOTION001       YES		    ON		    ON		ON		Dim Lights                          #
#===============================================================================================#
  - alias: MOTION001
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: media_player.sharp_tv
        state: 'on'
      - condition: state
        entity_id: light.family_room
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.family_room
          brightness: 10
          color_temp: 154
          transition: 5

#===============================================================================================#
#   Automation      It's Dark 	Motion		TV		Lights	ACTION                              #
#   MOTION002       YES		    ON		    ON		OFF		Dim Lights                          #
#===============================================================================================#
  - alias: MOTION002
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: media_player.sharp_tv
        state: 'on'
      - condition: state
        entity_id: light.family_room
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.family_room
          brightness: 10
          color_temp: 154
          transition: 5

#===============================================================================================#
#   Automation      It's Dark 	Motion		TV		Lights	ACTION                              #
#   MOTION003       YES		    ON		    OFF		ON		Increase the brightness to 100%     #
#===============================================================================================#
  - alias: MOTION003
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: media_player.sharp_tv
        state: 'off'
      - condition: state
        entity_id: light.family_room
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.family_room
          brightness: 255
          color_temp: 154
          transition: 5

#===============================================================================================#
#   Automation      It's Dark 	Motion		TV		Lights	ACTION                              #
#   MOTION004       YES		    ON		    OFF		OFF		Turn Lights ON at 100% brightness   #
#===============================================================================================#
  - alias: MOTION004
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: media_player.sharp_tv
        state: 'off'
      - condition: state
        entity_id: light.family_room
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.family_room
          brightness: 255
          color_temp: 154
          transition: 5
  
#===============================================================================================#
#   Automation      It's Dark 	Motion		TV		Lights	ACTION                              #
#   MOTION005       YES		    OFF		    ON		ON		Lights OFF                          #
#===============================================================================================#        
  - alias: MOTION005
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor
      from: 'on'
      to: 'off'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: media_player.sharp_tv
        state: 'on'
      - condition: state
        entity_id: light.family_room
        state: 'on'      
    action:
      - service: light.turn_off
        data:
          entity_id: light.family_room
          transition: 5

#===============================================================================================#
#   Automation      It's Dark 	Motion		TV		Lights	ACTION                              #        
#   MOTION006       YES		    OFF		    ON		OFF		Don't to anything                   #
#===============================================================================================#       

#===============================================================================================#
#   Automation      It's Dark 	Motion		TV		Lights	ACTION                              #        
#   MOTION007       YES		    OFF		    OFF		ON		Turn Lights OFF                     #
#===============================================================================================#
  - alias: MOTION007
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor
      from: 'on'
      to: 'off'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: media_player.sharp_tv
        state: 'off'
      - condition: state
        entity_id: light.family_room
        state: 'on'      
    action:
      - service: light.turn_off
        data:
          entity_id: light.family_room
          transition: 5
  
#===============================================================================================#
#   Automation      It's Dark 	Motion		TV		Lights	ACTION                              #
#   MOTION008       YES		    OFF		    OFF		OFF		Don't to anything                   #
#===============================================================================================#
  
###############################################################################
# Motion Sensor - Upstairs  
###############################################################################  
  - alias: Upstairs Motion ON
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor_2
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_1
          rgb_color: [224,175,102]
          brightness: 10
          #color_temp: 366
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_2
          rgb_color: [224,175,102]
          brightness: 10
          #color_temp: 366

  - alias: Upstairs Motion OFF
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor_2
      from: 'on'
      to: 'off'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_1
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_2

###############################################################################
#  Turn On Front room light When Motion detected, and turn OFF when no motion
#    -> Only during night
###############################################################################
  - alias: Front Room Motion ON
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.tradfri_bulb_e26_ws_opal_980lm
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.tradfri_bulb_e26_ws_opal_980lm

  - alias: Front Room Motion OFF
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
      from: 'on'
      to: 'off'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.tradfri_bulb_e26_ws_opal_980lm
        state: 'on' 
    action:
      - service: light.turn_off
        data:
          entity_id: light.tradfri_bulb_e26_ws_opal_980lm