###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   WatchDog
#   @description    :   Watchdog Automations
###############################################################################

homeassistant:
  customize:
    group.watchdog_automations:
      order: 58

    input_boolean.working_in_garage:
      friendly_name: Working in Garage
      #icon: mdi:worker
    automation.garage_lights_watchdog:
      friendly_name: Garage Lights Watchdog
      #icon: mdi:timer
    automation.guest_bedroom_1_light_watchdog:
      friendly_name: Guest Bedroom 1 Light Watchdog
     # icon: mdi:timer
    automation.guest_bedroom_2_light_watchdog:
      friendly_name: Guest Bedroom 2 Light Watchdog
    #  icon: mdi:timer
    automation.kids_bedroom_light_watchdog:
      friendly_name: Kids Bedroom Light Watchdog
     # icon: mdi:timer
    automation.prayer_room_light_watchdog:
      friendly_name: Prayer Room Light Watchdog
     # icon: mdi:timer

group:
  Watchdog Automations:
    entities:
      - automation.backyard_light_watchdog
      - automation.frontroom_light_watchdog
      - automation.frontyard_light_watchdog
      - automation.garage_lights_watchdog
      - automation.guest_bedroom_1_light_watchdog
      - automation.kids_bedroom_light_watchdog
      - automation.guest_bedroom_2_light_watchdog
      - automation.single_car_garage_door_watchdog
      - automation.home_security_system_watchdog_10_minutes
      - automation.home_security_system_watchdog_30_minutes
      - automation.working_in_garage_watchdog
      - automation.two_car_garage_door_watchdog

input_boolean:
  working_in_garage:
    name: Working in Garage
    initial: off

automation:
  - alias: Working In Garage WatchDog
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - input_boolean.working_in_garage
        to: 'on'
        for: 
          hours: 2
    action:
      - service: script.notify_me
        data: { "value1":"It has been two hours, are you still working in the garage?", "value2":" Changing the status to 'Not working'!"}
      - service: input_boolean.turn_off
        entity_id: input_boolean.working_in_garage
  
  - alias: Single Car garage Door WatchDog
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.ecolink_garage_door_tilt_sensor_sensor_5_0
        to: 'on'
        for: 
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.working_in_garage
        state: 'off'
    action:
      - service: script.notify_me
        data: {"value1":"Single Car Garage Door is OPEN for more than 5 minutes!", "value2":""}
      - service: script.voice_notify
        data_template:
          value1: "Attention! Your single car garage door is open for more than 5 minutes."
          value2: ""
  
  - alias: Two Car garage Door WatchDog
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.ecolink_garage_door_tilt_sensor_sensor_4_0
        to: 'on'
        for: 
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.working_in_garage
        state: 'off'
    action:
      - service: script.notify_me
        data: {"value1":"Your Two Car Garage Door is OPEN for more than 5 minutes!", "value2":""}
      - service: script.voice_notify
        data_template:
          value1: "Attention! Your two car garage door is open for more than 5 minutes."
          value2: ""
          
  - alias: Home Security System WatchDog 10 minutes
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - alarm_control_panel.simplisafe
        to: 'disarmed'
        for: 
          minutes: 10
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
      - service: script.notify_me
        data: {"value1":"Home Security System is OFF for more than 10 minutes!", "value2":""}
      - service: script.voice_notify
        data_template:
          value1: "Attention! The Home Security System is OFF for more than 10 minutes!"
          value2: ""
          
  - alias: Home Security System WatchDog 30 minutes
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - alarm_control_panel.simplisafe
        to: 'disarmed'
        for: 
          minutes: 30
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
      - service: script.notify_me
        data: {"value1":"Home Security System is OFF for more than 30 minutes!", "value2":""}
      - service: script.voice_notify
        data_template:
          value1: "Attention! The Home Security System is OFF for more than 30 minutes! This is the last reminder!"
          value2: ""
  
  # - alias: Frontroom Light WatchDog
    # initial_state: true
    # trigger:
      # - platform: state
        # entity_id:
          # - switch.wemoswitch1
        # to: 'on'
        # for:
          # minutes: 5
    # condition:
      # - condition: state
        # entity_id: sun.sun
        # state: 'above_horizon'
    # action:
      # - service: switch.turn_off
        # data_template:
          # entity_id: "{{ trigger.entity_id }}"
      # - service: script.notify_me
        # data_template:
          # value1: >
            # {{ trigger.to_state.attributes.friendly_name }} is ON. Saving power by turning it off!
          # value2: ""
  
  - alias: Frontyard Light WatchDog
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - switch.wemofrontporchlightswitch
        to: 'on'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} is ON during the day time. Saving power by turning it off!
          value2: ""
  
  - alias: Backyard Light WatchDog
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - switch.wemobackyardlightswitch
        to: 'on'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} is ON during the day time. Saving power by turning it off!
          value2: ""
  
  - alias: Garage Lights WatchDog
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - switch.garage_lights
        to: 'on'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: input_boolean.working_in_garage
        state: 'off'
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      - service: script.notify_me
        data_template:
          value1: >
            {{ trigger.to_state.attributes.friendly_name }} are left ON for about 5 minutes. Saving power by turning it off!
  
  # - alias: Guest Bedroom 1 Light WatchDog
    # initial_state: true
    # trigger:
      # - platform: state
        # entity_id:
          # - switch.guest_bedroom_1
        # to: 'on'
        # for:
          # minutes: 15
    # action:
      # - service: switch.turn_off
        # data_template:
          # entity_id: "{{ trigger.entity_id }}"
      # - service: script.notify_me
        # data_template:
          # value1: >
            # {{ trigger.to_state.attributes.friendly_name }} lights are left ON for 25 minutes. Saving power by turning it off!
          # value2: ""
  
  - alias: Guest Bedroom 2 Light WatchDog
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - switch.guest_bedroom_2
        to: 'on'
        for:
          minutes: 10
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      # - service: script.notify_me
        # data_template:
          # value1: >
            # {{ trigger.to_state.attributes.friendly_name }} lights are left ON for 10 minutes. Saving power by turning it off!
          # value2: ""
  
  - alias: Kids Bedroom Light WatchDog
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - switch.kids_bedroom
        to: 'on'
        for:
          minutes: 10
    action:
      - service: switch.turn_off
        data_template:
          entity_id: "{{ trigger.entity_id }}"
      # - service: script.notify_me
        # data_template:
          # value1: >
            # {{ trigger.to_state.attributes.friendly_name }} lights are left ON for 10 minutes. Saving power by turning it off!
          # value2: ""